/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('antdv-next/dist/button/index')['default']
    ADivider: typeof import('antdv-next/dist/divider/index')['default']
    ATypography: typeof import('antdv-next/dist/typography/index')['default']
    ATypographyLink: typeof import('antdv-next/dist/typography/index')['TypographyLink']
    ATypographyParagraph: typeof import('antdv-next/dist/typography/index')['TypographyParagraph']
    ATypographyText: typeof import('antdv-next/dist/typography/index')['TypographyText']
    ATypographyTitle: typeof import('antdv-next/dist/typography/index')['TypographyTitle']
  }
}
