/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AImage: typeof import('antdv-next')['Image']
    AImagePreviewGroup: typeof import('antdv-next')['ImagePreviewGroup']
    AStyleProvider: typeof import('antdv-next')['StyleProvider']
    StepForwardOutlined: typeof import('@antdv-next/icons')['StepForwardOutlined']
  }
}
