export default {
  AAffix: [{ name: 'Affix', path: 'affix' }],
  AButton: [{ name: 'Button', path: 'button' }],
  AAlert: [{ name: 'Alert', path: 'alert' }],
  AAnchor: [{ name: 'Anchor', path: 'anchor' }],
  ASpace: [{ name: 'Space', path: 'space' }],
  ADivider: [{ name: 'Divider', path: 'divider' }],
  ASpaceCompact: [{ name: 'SpaceCompact', path: 'space', as: 'SpaceCompact' }],
  ASpaceAddon: [{ name: 'SpaceAddon', path: 'space', as: 'SpaceAddon' }],
  AStyleProvider: [{ name: 'StyleProvider', path: 'style-provider' }],
  AFlex: [{ name: 'Flex', path: 'flex' }],
  AConfigProvider: [{ name: 'ConfigProvider', path: 'config-provider' }],
  ACol: [{ name: 'Col', path: 'grid', as: 'Col' }],
  ARow: [{ name: 'Row', path: 'grid', as: 'Row' }],
  ABadge: [{ name: 'Badge', path: 'badge' }],
  ABadgeRibbon: [{ name: 'BadgeRibbon', path: 'badge', as: 'BadgeRibbon' }],
  ATag: [{ name: 'Tag', path: 'tag' }],
  ACheckableTag: [{ name: 'CheckableTag', path: 'tag', as: 'CheckableTag' }],
  ACheckableTagGroup: [{ name: 'CheckableTag', path: 'tag', as: 'CheckableTagGroup' }],
  ALayout: [{ name: 'Layout', path: 'layout' }],
  ALayoutHeader: [{ name: 'LayoutHeader', path: 'layout', as: 'LayoutHeader' }],
  ALayoutFooter: [{ name: 'LayoutFooter', path: 'layout', as: 'LayoutFooter' }],
  ALayoutContent: [{ name: 'LayoutContent', path: 'layout', as: 'LayoutContent' }],
  ALayoutSider: [{ name: 'LayoutSider', path: 'layout', as: 'LayoutSider' }],
  AEmpty: [{ name: 'Empty', path: 'empty' }],
  AResult: [{ name: 'Result', path: 'result' }],
  ASpin: [{ name: 'Spin', path: 'spin' }],
  ASkeleton: [{ name: 'Skeleton', path: 'skeleton' }],
  ASkeletonButton: [{ name: 'SkeletonButton', path: 'skeleton', as: 'SkeletonButton' }],
  ASkeletonAvatar: [{ name: 'SkeletonAvatar', path: 'skeleton', as: 'SkeletonAvatar' }],
  ASkeletonInput: [{ name: 'SkeletonInput', path: 'skeleton', as: 'SkeletonInput' }],
  ASkeletonImage: [{ name: 'SkeletonImage', path: 'skeleton', as: 'SkeletonImage' }],
  ASkeletonNode: [{ name: 'SkeletonNode', path: 'skeleton', as: 'SkeletonNode' }],
  AStatistic: [{ name: 'Statistic', path: 'statistic' }],
  AStatisticTimer: [{ name: 'StatisticTimer', path: 'statistic', as: 'StatisticTimer' }],
  ADescriptions: [{ name: 'Descriptions', path: 'descriptions' }],
  ATimeline: [{ name: 'Timeline', path: 'timeline' }],
  AWatermark: [{ name: 'Watermark', path: 'watermark' }],
  AQrcode: [{ name: 'QRCode', path: 'qrcode' }],
  ACollapse: [{ name: 'Collapse', path: 'collapse' }],
  ATooltip: [{ name: 'Tooltip', path: 'tooltip' }],
  ASegmented: [{ name: 'Segmented', path: 'segmented' }],
  APopover: [{ name: 'Popover', path: 'popover' }],
  APopconfirm: [{ name: 'Popconfirm', path: 'popconfirm' }],
  AFloatButton: [{ name: 'FloatButton', path: 'float-button' }],
  AFloatBackTop: [{ name: 'BackTop', path: 'float-button', as: 'BackTop' }],
  AFloatButtonGroup: [{ name: 'FloatButtonGroup', path: 'float-button', as: 'FloatButtonGroup' }],
  AMenu: [{ name: 'Menu', path: 'menu' }],
  ADropdown: [{ name: 'Dropdown', path: 'dropdown' }],
  ATour: [{ name: 'Tour', path: 'tour' }],
  ABreadcrumb: [{ name: 'Breadcrumb', path: 'breadcrumb' }],
  AAvatar: [{ name: 'Avatar', path: 'avatar' }],
  AAvatarGroup: [{ name: 'AvatarGroup', path: 'avatar', as: 'AvatarGroup' }],
  AForm: [{ name: 'Form', path: 'form' }],
  AFormItem: [{ name: 'FormItem', path: 'form', as: 'FormItem' }],
  ACheckbox: [{ name: 'Checkbox', path: 'checkbox' }],
  ACheckboxGroup: [{ name: 'CheckboxGroup', path: 'checkbox', as: 'CheckboxGroup' }],
  ARadio: [{ name: 'Radio', path: 'radio' }],
  ARadioGroup: [{ name: 'RadioGroup', path: 'radio', as: 'RadioGroup' }],
  ARadioButton: [{ name: 'RadioButton', path: 'radio', as: 'RadioButton' }],
  ASwitch: [{ name: 'Switch', path: 'switch' }],
  AColorPicker: [{ name: 'ColorPicker', path: 'color-picker' }],
  ASlider: [{ name: 'Slider', path: 'slider' }],
  AInput: [{ name: 'Input', path: 'input' }],
  AInputSearch: [{ name: 'InputSearch', path: 'input',  as: 'InputSearch' }],
  AInputPassword: [{ name: 'InputPassword', path: 'input',  as: 'InputPassword' }],
  AInputOtp: [{ name: 'InputOTP', path: 'input',  as: 'InputOtp' }],
  AInputGroup: [{ name: 'InputGroup', path: 'input',  as: 'InputGroup' }],
  AInputNumber: [{ name: 'InputNumber', path: 'input-number' }],
  ATextarea: [{ name: 'TextArea', path: 'input',  as: `TextArea` }],
  ATypography: [{ name: 'Typography', path: 'typography' }],
  ATypographyText: [{ name: 'TypographyText', path: 'typography', as: 'TypographyText' }],
  ATypographyTitle: [{ name: 'TypographyTitle', path: 'typography', as: 'TypographyTitle' }],
  ATypographyParagraph: [{ name: 'TypographyParagraph', path: 'typography', as: 'TypographyParagraph' }],
  ATypographyLink: [{ name: 'TypographyLink', path: 'typography', as: 'TypographyLink' }],
  ATabs: [{ name: 'Tabs', path: 'tabs' }],
  ATabPane: [{ name: 'TabPane', path: 'tabs', as: 'TabPane' }],
  ASelect: [{ name: 'Select', path: 'select' }],
  ASelectOption: [{ name: 'SelectOption', path: 'select', as: 'SelectOption' }],
  ASelectOptGroup: [{ name: 'SelectOptGroup', path: 'select', as: 'SelectOptGroup' }],
  ASplitter: [{ name: 'Splitter', path: 'splitter' }],
  ASplitterPanel: [{ name: 'SplitterPanel', path: 'splitter', as: 'SplitterPanel' }],
  ACard: [{ name: 'Card', path: 'card' }],
  ACardGrid: [{ name: 'CardGrid', path: 'card', as: 'CardGrid' }],
  ACardMeta: [{ name: 'CardMeta', path: 'card', as: 'CardMeta' }],
  AMasonry: [{ name: 'Masonry', path: 'masonry' }],
  ARate: [{ name: 'Rate', path: 'rate' }],
  AProgress: [{ name: 'Progress', path: 'progress' }],
  ADrawer: [{ name: 'Drawer', path: 'drawer' }],
  AModal: [{ name: 'Modal', path: 'modal' }],
  ASteps: [{ name: 'Steps', path: 'steps' }],
  AImage: [{ name: 'Image', path: 'image' }],
  AImagePreviewGroup: [{ name: 'ImagePreviewGroup', path: 'image', as: 'ImagePreviewGroup' }],
  AApp: [{ name: 'App', path: 'app' }],
  ATree: [{ name: 'Tree', path: 'tree' }],
  ADirectoryTree: [{ name: 'DirectoryTree', path: 'tree', as: 'DirectoryTree' }],
  ATreeSelect: [{ name: 'TreeSelect', path: 'tree-select' }],
  AUpload: [{ name: 'Upload', path: 'upload' }],
  AUploadDragger: [{ name: 'UploadDragger', path: 'upload', as: 'UploadDragger' }],
  APagination: [{ name: 'Pagination', path: 'pagination' }],
  ATransfer: [{ name: 'Transfer', path: 'transfer' }],
  AMentions: [{ name: 'Mentions', path: 'mentions' }],
  ACarousel: [{ name: 'Carousel', path: 'carousel' }],
  ACascader: [{ name: 'Cascader', path: 'cascader' }],
  ATable: [{ name: 'Table', path: 'table' }],
  ATableColumn: [{ name: 'TableColumn', path: 'table', as: 'Column' }],
  ATableSummary: [{ name: 'TableSummary', path: 'table', as: 'Summary' }],
  ATableSummaryRow: [{ name: 'TableSummaryRow', path: 'table', as: 'SummaryRow' }],
  ATableSummaryCell: [{ name: 'TableSummaryCell', path: 'table', as: 'SummaryCell' }],
  ACalendar: [{ name: 'Calendar', path: 'calendar' }],
  ADatePicker: [{ name: 'DatePicker', path: 'date-picker' }],
  ARangePicker: [{ name: 'RangePicker', path: 'date-picker', as: 'DateRangePicker' }],
  ATimePicker: [{ name: 'TimePicker', path: 'time-picker' }],
  ATimeRangePicker: [{ name: 'TimeRangePicker', path: 'time-picker', as: 'TimeRangePicker' }],
  AAutoComplete: [{ name: 'AutoComplete', path: 'auto-complete' }],
  AAutoCompleteOption: [{ name: 'AutoCompleteOption', path: 'auto-complete', as: 'Option' }],
} as Record<string, { name: string, path: string, as?: string }[]>
